### ISSUE TITLE
Páginas guías

### ISSUE THREAD

**Issue by carolinajimenez26** [jdiegoh3/gameproyect_pygame#17]
### Scrolling background

> http://stackoverflow.com/questions/14354171/add-scrolling-to-a-platformer-in-pygame
> http://stackoverflow.com/questions/17240442/how-to-make-the-background-continuously-scrolling-with-pygame
> https://www.youtube.com/watch?feature=player_embedded&v=RZeQuArHTaM

**Comment by carolinajimenez26** [comment]
### SuperMarioBros Pygame

> https://github.com/Thickney/PyGameSMB

**Comment by h3ct0rjs** [comment]
You need to add a proper description in the readme file,  Make a quick video about the game or images related with the game, e.g [Space Invaders](https://github.com/heticor915/VideoJuego/tree/master/SpaceInvaders) or [general Description](https://github.com/heticor915/VideoJuego/), It is the final version of the game? or you need to add something?

**Comment by carolinajimenez26** [comment]
@heticor915 the description of how is going to be developed the game is in the [Wiki](https://github.com/jdiegoh3/gameproyect_pygame/wiki/Plantilla-del-documento-de-dise%C3%B1o.). The game isn't finish, that's the reason of the poor README :p

**Comment by h3ct0rjs** [comment]
Nice :space_invader: , Whats the proper setup to test and run the Game,  I'd like to test it just curious about your game :smile:

**Comment by carolinajimenez26** [comment]
@heticor915 In this moment I'm working on "desdecero" branch, you can clone the repo and run it with the command: "python2.7 main.py", easy. I'll be waiting for your opinion :grinning:

**Comment by h3ct0rjs** [comment]
Hi  @carolinajimenez26  I was checking the branch and apparently it works fine,  What would you like to hear from me :question: , the game is in current development :point_up_2:  I can't give you right now my feedback,  but when you have more things let me know.  For now it seems like a  supertux :smile: check this out [Official SIte.](http://supertuxproject.org/) . The background image  is appropriate and all the sounds too.

**Comment by h3ct0rjs** [comment]
@carolinajimenez26 @jdiegoh3  Are you going to document all the related work?, if you want I can help you using my latex template that looks like : 
https://github.com/heticor915/VideoJuego/blob/master/SpaceInvaders/ManualJuego/Documentacion.pdf
Latex template will be the same as : https://github.com/heticor915/VideoJuego/blob/master/SpaceInvaders/ManualJuego/Documentacion.tex

**Comment by carolinajimenez26** [comment]
Wow @heticor915 , it is so cool. I have to start learning latex, but I'm not sure if we're going to implement it to this game. Thanks for the source, sure I can learn from it

**Comment by carolinajimenez26** [comment]
@heticor915 Hello Hector, how are you doing? I just pushed the first final version of this game on the master, you can check it and tell us your opinion :smile: thanks, I'll be waiting for it

**Comment by h3ct0rjs** [comment]
Hi @carolinajimenez26 @jdiegoh3 this is my quick review of your game, I have had some details that are important for the performance of the game.

After run `python main.py` it takes a long time(40 seconds, you can reproduce this measure using time utility available in any Unix/Gnu-linux OS, of course there are others  clock timing tools but this is ok.) to open the game options(menu) due to the multiple load images that represent the quick video in the background, sometimes this affect directly to the game performance and can crash the computer due to memory limits. As it's shown below you can see the first time How many memory I was using **106MB** of ram memory,after that it seems that it takes approximately **1356MB**  extra ram memory. You need to do a quick optimization to the time of execution.
![before](http://i.imgur.com/9SrRm2Q.png)

![after](http://i.imgur.com/smLkNFq.png)

I haven't check if it's a problem of the number of images/or size of each image but this increase the amount of memory  in usage by the game. 

The other thing is the window resolution is fixed(this is okay if you're doing test or if previously set this in the game settings), but it should be autoresize.  The cool  :smile:  part of the main menu is the sound and of course the background video, this was an excellent choice.The other options  are operational. The game itself seems cool.I was wondering why in the start if I don't move nothing you die, the debug message in my terminal printed:
 life :  83.5
life :  67.0
life :  50.5
life :  34.0
life :  17.5
life :  1.0
life :  -15.5
Perdiste
But if you don't move nothing and there is not an enemy why will you die ?.
